version: "3"
services:
  app:
    restart: always
    build: .
    command: >
      bash -c "
      python3 manage.py collectstatic --no-input &&
      python3 manage.py migrate &&
      gunicorn --timeout=30 --workers=4 --bind :8000 simple_shop.wsgi:application"
    volumes:
      - "./staticFiles:/current/staticFiles"
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  db:
    restart: always
    image: mysql:5.7
    # volumes:
    #   - "./mysql:/var/lib/mysql"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - db_network

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - "./staticFiles:/current/staticFiles"
      - "./config/nginx:/etc/nginx/conf.d"
    depends_on:
      - app
    networks:
      - web_network

  redis:
    image: "redis:alpine"

  celery-beat:
    build: .
    command: celery -A simple_shop -l debug worker -B
    depends_on:
      - app
      - redis

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
