# Generated by Django 2.2 on 2019-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_pcs',
            field=models.IntegerField(max_length=20),
        ),
    ]
