# Generated by Django 2.2 on 2019-12-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
